# .pre-commit-config.yaml
# Confluence Doc: https://safe-security.atlassian.net/l/cp/wMVkxTC3
repos:

# ---- Common Pre-commit hooks ---- start
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        stages: [pre-commit]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args:
          - --severity=error # Valid values in order of severity are error, warning, info and style
        stages: [pre-commit]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        stages: [pre-commit]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
        args:
          - '-ignore=label "ubuntu-latest-(4|8|16)core" is unknown'
        stages: [pre-commit]

# Commit Message Linting. Run below command to install commitlint
# npm install --save-dev @commitlint/{config-conventional,cli}
  - repo: local
    hooks:
      - id: commitlint
        name: Commit Message Linting
        entry: npx commitlint --edit
        language: system
        stages: [commit-msg]

# ---- Common Pre-commit hooks ---- End

# ---- Golang Pre-commit hooks ---- start

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
        - id: go-fmt
        - id: go-imports
        - id: no-go-testing
        - id: golangci-lint
          stages: [pre-commit]

# ---- Golang Pre-commit hooks ---- End