name: PR Title Check

env:
  CONVENTIONAL_COMMIT_REGEX: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title;
            const pattern = new RegExp(process.env.CONVENTIONAL_COMMIT_REGEX);
            
            if (!pattern.test(title)) {
              core.setFailed(
                '❌ PR title must follow convention:\n' +
                '   <type>[optional scope]: <description>\n\n' +
                '   Example: feat(auth): add login feature\n' +
                '   📚 See conventionalcommits.org for more details'
              );
            }